
function blocks/find_budding_amethyst
function blocks/find_coal_ore
function blocks/find_copper_ore
function blocks/find_diamond_ore
function blocks/find_emerald_ore
function blocks/find_gold_ore
function blocks/find_iron_ore
function blocks/find_lapis_ore
function blocks/find_redstone_ore

function blocks/find_ancient_debris
function blocks/find_quartz_ore
