
function blocks/find_budding_amethyst_double_distance
function blocks/find_coal_ore_double_distance
function blocks/find_copper_ore_double_distance
function blocks/find_diamond_ore_double_distance
function blocks/find_emerald_ore_double_distance
function blocks/find_gold_ore_double_distance
function blocks/find_iron_ore_double_distance
function blocks/find_lapis_ore_double_distance
function blocks/find_redstone_ore_double_distance
